spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.44.154.184:3306/academic
    username: root
    password: RUANFEN-front
  mail:
    host: smtp.qq.com
    username: 2381854695@qq.com
    password: kzclxmzzumizdhid
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
  # Redis 连接信息
  redis:
    host: 192.168.0.141
    port: 6379
    database: 0
#    password: your_password

#canal:
#  server: 127.0.0.1:11111
#  destination: example


mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.ruanfen.enums